### ISSUE TITLE
Question: possible to capture content ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [uptechteam/MotionViews-Android#1]
Suppose I've added some texts, images, etc...
And now I want to save it as a bitmap, and send it, how do I do it?

**Comment by AndriyBas** [comment]
@AndroidDeveloperLB Check class `MotionView.java`, method `public Bitmap getThumbnailImage()`. It returns the bitmap with all current images, text (with the current size of the canvas)

**Comment by AndroidDeveloperLB** [comment]
Why is it called "getThumbnailImage" ? How do you get to choose the size of
this bitmap?
Also, BTW, does this library support vectorDrawable?

**Comment by AndriyBas** [comment]
@AndroidDeveloperLB the library does not support vectorDrawable, it works with Bitmaps

**Comment by AndroidDeveloperLB** [comment]
and how do I choose the bitmap size for it?

**Comment by AndriyBas** [comment]
@AndroidDeveloperLB any bitmap size works (unless it throws `OutOfMemory`)
