### ISSUE TITLE
How to  specify the location of the bitmap?

### ISSUE THREAD

**Issue by VamChao** [uptechteam/MotionViews-Android#13]
I want to place the bitmap according to coordinate shots at the specified location
, then what should I do?
Thank you!

**Comment by AndriyBas** [comment]
@VamChao in MotionEntity there's a method `moveCenterTo(PointF moveToCenter)`. It accepts absolute coordinates in params. You can use it to move text entity whenever you want. (See `MainActivity`, method `addTextSticker` for how it is used)
