### ISSUE TITLE
increase and decrease height of Image Entity by click of buttons or seekbar

### ISSUE THREAD

**Issue by AnkurJagani** [uptechteam/MotionViews-Android#22]
It would be very nice if we can increase and decrease height of Image Entity **by click of buttons or seekbar**. like you have done in TextEnity for font size. 

_Five star for this library is less i think._

**Comment by AndriyBas** [comment]
Hello, @AnkurJagani. Just implement it in a similar way as it's done in `TextEntity`. All the positions are relative, all you need to do is just increase the size of the entity, all the other coordinates will adjust automatically. And redraw.
