### ISSUE TITLE
Remove button - how to add remove button on corner of text box

### ISSUE THREAD

**Issue by vrsrohit** [uptechteam/MotionViews-Android#27]
Hello thanx for ur code its very useful for me but i am not able to add a remove button in the text box  
i.e, it must dissapear when text box dissapears 
please reply ASAP

**Comment by AndriyBas** [comment]
hello @vrsrohit . In `MotionEntity.java` there are methods `draw()` and `drawSelectedBg()`. Use them to draw anything on top you need.

**Comment by superdiazzz** [comment]
Hi i have similarly problem, but i have drawn it but now i confused to make listener on it? @AndriyBas Could you give me some advice?
