### ISSUE TITLE
Force finishing activity team.uptech.motionviews/.ui.MainActivity

### ISSUE THREAD

**Issue by ghanatep** [uptechteam/MotionViews-Android#28]
I am using same sample app, I just added one LaunchActivity and in this activity I have only a start button nothing else, onclick I am starting MainActivity of sample app. 2-3 times if I navigate between these two activities(doing operations like adding text in MainActivity and increase the size). The app is crashing.
**team.uptech.motionviews W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (720x17777, max=8192x8192)**
Complete logcat:
12-14 11:45:20.450 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:45:22.440 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:45:23.940 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:45:25.770 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:45:30.000 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:45:35.250 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:45:38.030 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:46:02.370 22047-22047/team.uptech.motionviews W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
12-14 11:46:27.480 15995-15995/? W/Conv2QueryExtension: Conv2Query not enabled due to current app [team.uptech.motionviews] not in whitelist
12-14 11:46:36.370 22047-22056/team.uptech.motionviews A/libc: Fatal signal 11 (SIGSEGV) at 0x00000006 (code=1), thread 22056 (FinalizerDaemon)
12-14 11:46:36.370 22047-22054/team.uptech.motionviews A/libc: Fatal signal 11 (SIGSEGV) at 0x00000004 (code=1), thread 22054 (Compiler)
12-14 11:46:37.030 478-22215/? W/ActivityManager:   Force finishing activity team.uptech.motionviews/.ui.MainActivity
12-14 11:46:37.100 478-543/? W/InputDispatcher: channel '223e24c8 team.uptech.motionviews/team.uptech.motionviews.ui.LaunchActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-14 11:46:37.100 478-543/? E/InputDispatcher: channel '223e24c8 team.uptech.motionviews/team.uptech.motionviews.ui.LaunchActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-14 11:46:37.120 478-4184/? W/InputDispatcher: Attempted to unregister already unregistered input channel '223e24c8 team.uptech.motionviews/team.uptech.motionviews.ui.LaunchActivity (server)'
12-14 11:46:37.280 22219-22219/team.uptech.motionviews E/IMGSRV: :0: PVRDRMOpen: TP3, ret = 50

**Comment by AndriyBas** [comment]
@ghanatep seems like you're trying to use too big Bitmap. decrease the bitmaps and try again.
