### ISSUE TITLE
How to set backgound image?

### ISSUE THREAD

**Issue by tushar091** [uptechteam/MotionViews-Android#29]
I want to set background image upon which to add stickers

**Comment by chacha13** [comment]
just add setBackgroundResource to the MotionView

**Comment by dhirensengar** [comment]
how to set Gallery image in MotionView as Background.
Plz help me

**Comment by dhirensengar** [comment]
I have done in this way to set MotionView background, but while saving image , its background doesn`t comes only selected sticker and Text are visible.

   File f = new File(getRealPathFromURI(Uri.parse(PicUri)));
        Drawable d = Drawable.createFromPath(f.getAbsolutePath());
        motionView.setBackground(d);

**Comment by jayarajm** [comment]
The image getting stretch when I set background. 
How can I set background image with aspectToFit?

**Comment by JayarajTrans** [comment]
I done with some customisation. 
Make normal motion entity and set non editable it is working good.

**Comment by jayarajm** [comment]
I done with some customisation. 
Make normal motion entity and set non editable it is working good.

**Comment by AndriyBas** [comment]
@jayarajm or you can just add another view (ex: `ImageView`) behind the `MotionView` and set it's params to whatever you want.

**Comment by JayarajTrans** [comment]
Thank you @AndriyBas

**Comment by NareshAskani** [comment]
> I done with some customisation.
> Make normal motion entity and set non editable it is working good.

hi, could you help with code, i am also tried in same process. but i am not able to figure out holyscale value. images not able to fit with in screen.
