### ISSUE TITLE
Not able to edit the sentence from particular point

### ISSUE THREAD

**Issue by rohitgarg29** [uptechteam/MotionViews-Android#32]
Hi,

I want to edit the sentence from particular point and show the cursor, is it possible?

Regards,
R

**Comment by AndriyBas** [comment]
hello, @rohitgarg29. Nope, now it is not possible to edit the sentence from a particular point. 
The implementation does not allow it currently.

**Comment by rohitgarg29** [comment]
Hello, @AndriyBas If not, is there possibility of showing cursor icon? Thanks for your quick response! 👍

**Comment by AndriyBas** [comment]
currently - not possible to show the cursor. Because the text is shown as a Bitmap. 
However, you can implement a solution to draw the line similar to cursor where you need + add logic to refresh it periodically to make it blink like a cursor.

**Comment by mwshubham** [comment]
Are you planning to add this feature? This seems to be a good one.
Thanks in advance.
