### ISSUE TITLE
set Background 

### ISSUE THREAD

**Issue by FitApps7** [uptechteam/MotionViews-Android#33]
how to set picture in background(moveable), as photo frame?
I want to use it in inserting photos in static frames, but pics should be moveable.

**Comment by AndriyBas** [comment]
@FitApps7 just add your ImageView with a frame on top of thee MotionView, and make it not clickable.
Or, alternatively, modify the MotinoView to always draw your frame on top of the pic.

**Comment by FitApps7** [comment]
thanks
