### ISSUE TITLE
Out of memory problem

### ISSUE THREAD

**Issue by berviantoleo** [uptechteam/MotionViews-Android#34]
Hello, I want to try include this motion views to my application. I want to initialize some text sticker first. But, when I start the activity, I have out of memory problem when create bitmap. How I solve this problem? If need stacktrace the exception, I will write it down.

Thank you.

**Comment by AndriyBas** [comment]
@berviantoleo yeah, attach the stack trace and the code how you initialize all the classes. 
Does the example app work for you when you run it? if yes - most likely you missed something in the initialization.

**Comment by berviantoleo** [comment]
Example app work for me. I think the problem is when I tried init sticker with size too big, so when I created the bitmap will raised out of memory. This issue may be closed.
