### ISSUE TITLE
How to save the position of sticker?

### ISSUE THREAD

**Issue by berviantoleo** [uptechteam/MotionViews-Android#35]
I have set the position some sticker with drag to any position. When I try to lock my screen, the position become to initial position (my initial position in center of screen). How I save the location of some sticker?

+ I face this problem when for the first launch activity is landscape, when I lock the screen (I think this make my activity comes portrait), so when I open the activity it change from portrait to landscape.

**Comment by AndriyBas** [comment]
It's a typical Android task - to save the Activity Instance state. check the method `onSaveInstanceState` in the Activity. Save your sticker positions and later restore them.
