### ISSUE TITLE
insert image from device

### ISSUE THREAD

**Issue by FitApps7** [uptechteam/MotionViews-Android#36]
How I can insert image from gallery or camera in place of sticker?

I have code to open gallery or camera that give bitmap, but next I want to move that image in place of sticker, But how is it possible???

**Comment by AndriyBas** [comment]
@FitApps7 just convert your image to Bitmap and create an `ImageEntity` (it accepts a bitmap in the constructor).

**Comment by FitApps7** [comment]
thanks, work well
