### ISSUE TITLE
Deleting an entity

### ISSUE THREAD

**Issue by kiaanpillay** [uptechteam/MotionViews-Android#4]
Correct way to delete and entity? Do we just remove it from the List<MotionEntities>? Or do we have to release the memory somehow?

**Comment by AndriyBas** [comment]
@kiaanpillay just removing it from the list would be fine, no memory leaks. However, if you want to optimize memory usage as much as possible, you can call `.release()` on the entity, this will recycle entity bitmap if any immediately (calling `bitmap.recycle()`)
