### ISSUE TITLE
Move a TextEntity up when keyboard displayed

### ISSUE THREAD

**Issue by kiaanpillay** [uptechteam/MotionViews-Android#5]
Any way to move a text Entity up if a keyboard is covering it then move it back down when complete?

**Comment by AndriyBas** [comment]
@kiaanpillay in `MotionEntity` there's a method `moveCenterTo(PointF moveToCenter)`. You can use it to move text entity whenever you want. (See `MainActivity`, method `addTextSticker` for how it is used)
