### ISSUE TITLE
Unlimited Scaling?

### ISSUE THREAD

**Issue by kiaanpillay** [uptechteam/MotionViews-Android#6]
Is there a way to keep scaling even when the green border touches the bounds? I want to keep scaling beyond that if possible like on Snapchat or Instagram

**Comment by AndriyBas** [comment]
@kiaanpillay see `Layer.java` and `TextLayer.java`. They both have variables `MAX_SCALE` and `MIN_SCALE`, update them if you want to change scaling options. NOTE: be aware that image quality (especially of text) will change if you scale too much.
