### ISSUE TITLE
How to make boundary of TextEntity equal to exact textsize?

### ISSUE THREAD

**Issue by kiaanpillay** [uptechteam/MotionViews-Android#7]
There is always a bit of a margin on the left and right of Text Entities, not sure about Image enities. Is there a way to remove this so it is basically "Wrap_content"?

**Comment by kiaanpillay** [comment]
Great project!

**Comment by kiaanpillay** [comment]
Any update?

**Comment by AndriyBas** [comment]
Hello @kiaanpillay . The text entity is designed to be of the same width (and flexible height).
In class `TextEntity` method `createBitmap` the width of the `TextEntity` is defined as the `canvasWidth`. You can change it to the value you want (like the width of the text).

**Comment by AndriyBas** [comment]
is that what you were asking for ?
