### ISSUE TITLE
Shadow or outlined color on text

### ISSUE THREAD

**Issue by jenkhefter** [uptechteam/MotionViews-Android#8]
Hi, I wanna set a narrow outlined color to the text for its better visibility, can any body help me???

**Comment by AndriyBas** [comment]
@jenkhefter you'd probably want to use text Stroke. Search for "drawing text with stroke", probably this link would help: http://stackoverflow.com/questions/9044769/how-to-draw-text-with-different-stroke-and-fill-colors
