### ISSUE TITLE
Library problem

### ISSUE THREAD

**Issue by azzimfarid** [uptechteam/MotionViews-Android#9]
Hi i tried to compile this library in my gradle 'com.github.QuadFlask:colorpicker:0.0.12' but it is not working. This error keeps popping up:
Error:(27, 13) Failed to resolve: com.github.QuadFlask:colorpicker:0.0.12
<a href="openFile:C:/Users/MediaCliQ/Desktop/Cliqers Project/MotionViews/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by AndriyBas** [comment]
@azzimfarid just update QuadFlask lib to version `0.0.13` (see https://github.com/QuadFlask/colorpicker for reference)
